<?php

namespace Database\Seeders;

use App\Models\Roadmap;
use App\Models\Task;
use App\Models\User;
use Illuminate\Database\Seeder;

class AlgorithmsDataStructuresRoadmapSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::where('email', 'admin@roadmap.camp')->first();
        $phase8 = Roadmap::where('slug', 'phase-8-professional-skills')->first();

        $roadmap = Roadmap::create([
            'creator_id' => $admin->id ?? null,
            'title' => 'Algorithms & Data Structures Mastery',
            'description' => 'Master fundamental and advanced algorithms and data structures. Learn complexity analysis, problem-solving patterns, and practice with real coding challenges.',
            'slug' => 'algorithms-data-structures-mastery',
            'duration_days' => 30,
            'difficulty_level' => 'intermediate',
            'is_published' => true,
            'is_featured' => false,
            'order' => 15,
            'prerequisite_roadmap_id' => null,
        ]);

        $this->createTasks($roadmap);
    }

    protected function createTasks(Roadmap $roadmap): void
    {
        $tasks = [
            // Day 1: Fundamentals & Complexity Analysis
            [
                'title' => 'Big O Notation & Time Complexity',
                'description' => 'Understand algorithm analysis, Big O notation, time and space complexity. Learn to analyze and compare algorithms. Practice with problems that require complexity analysis.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Algorithms',
                'learning_objectives' => [],
                'skills_gained' => ['Algorithm Analysis', 'Big O', 'Complexity Analysis'],
                'tags' => ['big-o', 'complexity', 'analysis', 'algorithms'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=Mo4vesaut8g', 'title' => 'freeCodeCamp - Data Structures Course (Watch Introduction & Big O section)', 'type' => 'video'],
                    ['url' => 'https://bigocheatsheet.com', 'title' => 'Big O Cheat Sheet', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/find-numbers-with-even-number-of-digits/', 'title' => 'LeetCode #1295 - Find Numbers with Even Number of Digits', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/richest-customer-wealth/', 'title' => 'LeetCode #1672 - Richest Customer Wealth', 'type' => 'article'],
                    ['url' => 'https://www.amazon.com/Grokking-Algorithms-illustrated-programmers-curious/dp/1617292231', 'title' => '📚 Book: Grokking Algorithms (Chapter 1)', 'type' => 'article'],
                ],
            ],
            // Day 2: Arrays
            [
                'title' => 'Arrays & Two Pointers',
                'description' => 'Master array operations, two-pointer technique, sliding window, and common array problems.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Data Structures',
                'learning_objectives' => [],
                'skills_gained' => ['Arrays', 'Two Pointers', 'Sliding Window', 'Problem Solving'],
                'tags' => ['arrays', 'two-pointers', 'sliding-window'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=n60Dn0UsbEk', 'title' => 'freeCodeCamp - Arrays Deep Dive (Watch Arrays section)', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/two-sum/', 'title' => 'LeetCode #1 - Two Sum', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/', 'title' => 'LeetCode #26 - Remove Duplicates from Sorted Array', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/container-with-most-water/', 'title' => 'LeetCode #11 - Container With Most Water', 'type' => 'article'],
                    ['url' => 'https://www.amazon.com/Cracking-Coding-Interview-Programming-Questions/dp/0984782857', 'title' => '📚 Book: Cracking the Coding Interview (Arrays chapter)', 'type' => 'article'],
                ],
            ],
            // Day 3: Strings
            [
                'title' => 'String Algorithms',
                'description' => 'Learn string manipulation, pattern matching, palindromes, anagrams, and substring problems.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Data Structures',
                'learning_objectives' => [],
                'skills_gained' => ['Strings', 'Pattern Matching', 'String Algorithms'],
                'tags' => ['strings', 'palindromes', 'anagrams'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=V5hZoJ6uK-s', 'title' => 'freeCodeCamp - String Algorithms (2 hours)', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/valid-palindrome/', 'title' => 'LeetCode #125 - Valid Palindrome', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/valid-anagram/', 'title' => 'LeetCode #242 - Valid Anagram', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', 'title' => 'LeetCode #3 - Longest Substring Without Repeating Characters', 'type' => 'article'],
                    ['url' => 'https://www.amazon.com/Grokking-Algorithms-illustrated-programmers-curious/dp/1617292231', 'title' => '📚 Book: Grokking Algorithms (Strings section)', 'type' => 'article'],
                ],
            ],

            // Day 4-5: Linked Lists
            [
                'title' => 'Linked Lists Fundamentals',
                'description' => 'Understand linked lists: singly linked lists, doubly linked lists, insertion, deletion, and traversal.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Data Structures',
                'learning_objectives' => [],
                'skills_gained' => ['Linked Lists', 'Pointers', 'Data Structure Implementation'],
                'tags' => ['linked-lists', 'data-structures', 'pointers'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=njTh_OwMljA', 'title' => 'freeCodeCamp - Linked Lists Course (Watch first 2 hours)', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/delete-node-in-a-linked-list/', 'title' => 'LeetCode #237 - Delete Node in a Linked List', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/middle-of-the-linked-list/', 'title' => 'LeetCode #876 - Middle of the Linked List', 'type' => 'article'],
                    ['url' => 'https://visualgo.net/en/list', 'title' => 'VisuAlgo - Linked List Visualization', 'type' => 'article'],
                    ['url' => 'https://www.amazon.com/Introduction-Algorithms-3rd-MIT-Press/dp/0262033844', 'title' => '📚 Book: Introduction to Algorithms (CLRS) - Linked Lists', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Linked Lists Advanced',
                'description' => 'Solve advanced linked list problems: cycle detection, reversal, merge lists, and find middle.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Data Structures',
                'learning_objectives' => [],
                'skills_gained' => ['Advanced Linked Lists', 'Floyd\'s Algorithm', 'Problem Solving'],
                'tags' => ['linked-lists', 'cycles', 'reversal'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=njTh_OwMljA', 'title' => 'freeCodeCamp - Linked Lists Advanced Techniques', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/reverse-linked-list/', 'title' => 'LeetCode #206 - Reverse Linked List', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/linked-list-cycle/', 'title' => 'LeetCode #141 - Linked List Cycle', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/merge-two-sorted-lists/', 'title' => 'LeetCode #21 - Merge Two Sorted Lists', 'type' => 'article'],
                    ['url' => 'https://www.amazon.com/Cracking-Coding-Interview-Programming-Questions/dp/0984782857', 'title' => '📚 Book: Cracking the Coding Interview (Linked Lists)', 'type' => 'article'],
                ],
            ],
            // Day 6-7: Stacks & Queues
            [
                'title' => 'Stacks & Queues',
                'description' => 'Master stacks and queues: implementation, operations, and applications.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Data Structures',
                'learning_objectives' => [],
                'skills_gained' => ['Stacks', 'Queues', 'LIFO/FIFO'],
                'tags' => ['stacks', 'queues', 'data-structures'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=RBSGKlAvoiM', 'title' => 'freeCodeCamp - Stacks and Queues', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/valid-parentheses/', 'title' => 'LeetCode #20 - Valid Parentheses', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/implement-queue-using-stacks/', 'title' => 'LeetCode #232 - Implement Queue using Stacks', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/min-stack/', 'title' => 'LeetCode #155 - Min Stack', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Stack & Queue Applications',
                'description' => 'Practice stack and queue problems: monotonic stack, circular queue.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Data Structures',
                'learning_objectives' => [],
                'skills_gained' => ['Monotonic Stack', 'Circular Queue', 'Problem Solving'],
                'tags' => ['stacks', 'queues', 'monotonic-stack'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=FNZ5o9S9prU', 'title' => 'CS Dojo - Stack and Queue Problems', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/daily-temperatures/', 'title' => 'LeetCode #739 - Daily Temperatures', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/evaluate-reverse-polish-notation/', 'title' => 'LeetCode #150 - Evaluate Reverse Polish Notation', 'type' => 'article'],
                ],
            ],

            // Day 8-9: Hash Tables
            [
                'title' => 'Hash Tables & Hash Maps',
                'description' => 'Understand hashing: hash functions, collision resolution, hash maps, and common use cases.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Data Structures',
                'learning_objectives' => [],
                'skills_gained' => ['Hash Tables', 'Hashing', 'Hash Maps'],
                'tags' => ['hash-tables', 'hashing', 'data-structures'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=shs0KM3wKv8', 'title' => 'freeCodeCamp - Hash Tables Explained', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/contains-duplicate/', 'title' => 'LeetCode #217 - Contains Duplicate', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/ransom-note/', 'title' => 'LeetCode #383 - Ransom Note', 'type' => 'article'],
                    ['url' => 'https://visualgo.net/en/hashtable', 'title' => 'VisuAlgo - Hash Table', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Hash Table Problems',
                'description' => 'Solve hash table problems: two sum, group anagrams, frequency counting.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Data Structures',
                'learning_objectives' => [],
                'skills_gained' => ['Hash Map Applications', 'Frequency Counting', 'Optimization'],
                'tags' => ['hash-tables', 'optimization'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://leetcode.com/problems/group-anagrams/', 'title' => 'LeetCode #49 - Group Anagrams', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/top-k-frequent-elements/', 'title' => 'LeetCode #347 - Top K Frequent Elements', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/longest-consecutive-sequence/', 'title' => 'LeetCode #128 - Longest Consecutive Sequence', 'type' => 'article'],
                ],
            ],
            // Day 10-12: Trees
            [
                'title' => 'Binary Trees Basics',
                'description' => 'Learn tree fundamentals: binary trees, tree traversals (inorder, preorder, postorder).',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Data Structures',
                'learning_objectives' => [],
                'skills_gained' => ['Binary Trees', 'Tree Traversals', 'Recursion'],
                'tags' => ['trees', 'binary-trees', 'traversals', 'recursion'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=fAAZixBzIAI', 'title' => 'freeCodeCamp - Binary Trees Course', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/invert-binary-tree/', 'title' => 'LeetCode #226 - Invert Binary Tree', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', 'title' => 'LeetCode #104 - Maximum Depth of Binary Tree', 'type' => 'article'],
                    ['url' => 'https://visualgo.net/en/bst', 'title' => 'VisuAlgo - Binary Tree', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Binary Search Trees',
                'description' => 'Master BST: properties, insertion, deletion, search, and BST validation.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Data Structures',
                'learning_objectives' => [],
                'skills_gained' => ['BST', 'Tree Operations', 'Validation'],
                'tags' => ['bst', 'trees', 'data-structures'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=pYT9F8_LFTM', 'title' => 'freeCodeCamp - Binary Search Trees', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/validate-binary-search-tree/', 'title' => 'LeetCode #98 - Validate Binary Search Tree', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', 'title' => 'LeetCode #235 - Lowest Common Ancestor of BST', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Tree DFS & BFS',
                'description' => 'Practice tree problems using DFS and BFS: level order traversal, path finding.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Data Structures',
                'learning_objectives' => [],
                'skills_gained' => ['DFS', 'BFS', 'Tree Algorithms'],
                'tags' => ['trees', 'dfs', 'bfs'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=pcKY4hjDrxk', 'title' => 'Abdul Bari - DFS and BFS', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/binary-tree-level-order-traversal/', 'title' => 'LeetCode #102 - Binary Tree Level Order Traversal', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/same-tree/', 'title' => 'LeetCode #100 - Same Tree', 'type' => 'article'],
                ],
            ],

            // Day 13-14: Heaps
            [
                'title' => 'Heaps & Priority Queues',
                'description' => 'Learn heap data structure: min heap, max heap, heapify, and priority queue.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Data Structures',
                'learning_objectives' => [],
                'skills_gained' => ['Heaps', 'Priority Queues', 'Heap Sort'],
                'tags' => ['heaps', 'priority-queue', 'data-structures'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=HqPJF2L5h9U', 'title' => 'freeCodeCamp - Heaps Course', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/kth-largest-element-in-a-stream/', 'title' => 'LeetCode #703 - Kth Largest Element in a Stream', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/last-stone-weight/', 'title' => 'LeetCode #1046 - Last Stone Weight', 'type' => 'article'],
                    ['url' => 'https://visualgo.net/en/heap', 'title' => 'VisuAlgo - Heap', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Heap Problems',
                'description' => 'Practice heap problems: top K elements, merge K sorted lists.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Data Structures',
                'learning_objectives' => [],
                'skills_gained' => ['Heap Applications', 'Optimization', 'Problem Solving'],
                'tags' => ['heaps', 'top-k'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://leetcode.com/problems/kth-largest-element-in-an-array/', 'title' => 'LeetCode #215 - Kth Largest Element in an Array', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/k-closest-points-to-origin/', 'title' => 'LeetCode #973 - K Closest Points to Origin', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/task-scheduler/', 'title' => 'LeetCode #621 - Task Scheduler', 'type' => 'article'],
                ],
            ],
            // Day 15-18: Graphs
            [
                'title' => 'Graph Fundamentals',
                'description' => 'Introduction to graphs: directed vs undirected, weighted graphs, adjacency list.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Data Structures',
                'learning_objectives' => [],
                'skills_gained' => ['Graphs', 'Graph Representation', 'Graph Theory'],
                'tags' => ['graphs', 'data-structures', 'graph-theory'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=tWVWeAqZ0WU', 'title' => 'freeCodeCamp - Graph Algorithms (Watch first 2 hours)', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/find-center-of-star-graph/', 'title' => 'LeetCode #1791 - Find Center of Star Graph', 'type' => 'article'],
                    ['url' => 'https://visualgo.net/en/graphds', 'title' => 'VisuAlgo - Graph Structures', 'type' => 'article'],
                    ['url' => 'https://www.amazon.com/Introduction-Algorithms-3rd-MIT-Press/dp/0262033844', 'title' => '📚 Book: Introduction to Algorithms (Graphs chapter)', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Graph Traversal - DFS & BFS',
                'description' => 'Master graph traversal algorithms: depth-first search and breadth-first search.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Algorithms',
                'learning_objectives' => [],
                'skills_gained' => ['Graph DFS', 'Graph BFS', 'Graph Traversal'],
                'tags' => ['graphs', 'dfs', 'bfs', 'traversal'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=pcKY4hjDrxk', 'title' => 'Abdul Bari - Graph Traversal (Watch 2 hours)', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/number-of-islands/', 'title' => 'LeetCode #200 - Number of Islands', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/clone-graph/', 'title' => 'LeetCode #133 - Clone Graph', 'type' => 'article'],
                    ['url' => 'https://www.amazon.com/Grokking-Algorithms-illustrated-programmers-curious/dp/1617292231', 'title' => '📚 Book: Grokking Algorithms (Graphs chapter)', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Graph Problems',
                'description' => 'Solve graph problems: connected components, cycle detection, path finding.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Algorithms',
                'learning_objectives' => [],
                'skills_gained' => ['Graph Algorithms', 'Cycle Detection', 'Path Finding'],
                'tags' => ['graphs', 'algorithms'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://leetcode.com/problems/pacific-atlantic-water-flow/', 'title' => 'LeetCode #417 - Pacific Atlantic Water Flow', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/course-schedule/', 'title' => 'LeetCode #207 - Course Schedule', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/surrounded-regions/', 'title' => 'LeetCode #130 - Surrounded Regions', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Advanced Graph Algorithms',
                'description' => 'Learn topological sort and union-find data structure.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Algorithms',
                'learning_objectives' => [],
                'skills_gained' => ['Topological Sort', 'Union-Find'],
                'tags' => ['graphs', 'topological-sort', 'union-find'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=ID00PMy0-vE', 'title' => 'Abdul Bari - Topological Sort', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/redundant-connection/', 'title' => 'LeetCode #684 - Redundant Connection', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', 'title' => 'LeetCode #323 - Number of Connected Components', 'type' => 'article'],
                ],
            ],

            // Day 19-21: Sorting & Searching
            [
                'title' => 'Sorting Algorithms',
                'description' => 'Learn sorting algorithms: merge sort, quick sort, and their complexity.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Algorithms',
                'learning_objectives' => [],
                'skills_gained' => ['Sorting', 'Merge Sort', 'Quick Sort'],
                'tags' => ['sorting', 'algorithms', 'merge-sort', 'quick-sort'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=kPRA0W1kECg', 'title' => 'freeCodeCamp - Sorting Algorithms Course', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/sort-colors/', 'title' => 'LeetCode #75 - Sort Colors', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/merge-intervals/', 'title' => 'LeetCode #56 - Merge Intervals', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Binary Search Fundamentals',
                'description' => 'Master binary search: basic binary search, search variations.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Algorithms',
                'learning_objectives' => [],
                'skills_gained' => ['Binary Search', 'Search Algorithms', 'Optimization'],
                'tags' => ['binary-search', 'searching', 'algorithms'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=P3YID7liBug', 'title' => 'freeCodeCamp - Binary Search Course', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/binary-search/', 'title' => 'LeetCode #704 - Binary Search', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/search-a-2d-matrix/', 'title' => 'LeetCode #74 - Search a 2D Matrix', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Binary Search Applications',
                'description' => 'Practice binary search problems and optimization techniques.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Algorithms',
                'learning_objectives' => [],
                'skills_gained' => ['Binary Search Applications', 'Problem Solving', 'Optimization'],
                'tags' => ['binary-search', 'optimization'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', 'title' => 'LeetCode #153 - Find Minimum in Rotated Sorted Array', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/search-in-rotated-sorted-array/', 'title' => 'LeetCode #33 - Search in Rotated Sorted Array', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/time-based-key-value-store/', 'title' => 'LeetCode #981 - Time Based Key-Value Store', 'type' => 'article'],
                ],
            ],

            // Day 22-25: Dynamic Programming
            [
                'title' => 'Dynamic Programming Introduction',
                'description' => 'Introduction to DP: memoization, tabulation, and solving overlapping subproblems.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Algorithms',
                'learning_objectives' => [],
                'skills_gained' => ['Dynamic Programming', 'Memoization', 'Tabulation'],
                'tags' => ['dynamic-programming', 'dp', 'algorithms'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=oBt53YbR9Kk', 'title' => 'freeCodeCamp - Dynamic Programming Course (Watch first 2 hours)', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/climbing-stairs/', 'title' => 'LeetCode #70 - Climbing Stairs', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/min-cost-climbing-stairs/', 'title' => 'LeetCode #746 - Min Cost Climbing Stairs', 'type' => 'article'],
                    ['url' => 'https://www.amazon.com/Grokking-Algorithms-illustrated-programmers-curious/dp/1617292231', 'title' => '📚 Book: Grokking Algorithms (Dynamic Programming chapter)', 'type' => 'article'],
                ],
            ],
            [
                'title' => '1D Dynamic Programming',
                'description' => 'Solve 1D DP problems: Fibonacci, climbing stairs, house robber.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Algorithms',
                'learning_objectives' => [],
                'skills_gained' => ['1D DP', 'Space Optimization', 'Pattern Recognition'],
                'tags' => ['dynamic-programming', '1d-dp'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=oBt53YbR9Kk', 'title' => 'freeCodeCamp - DP Course (1D DP section)', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/house-robber/', 'title' => 'LeetCode #198 - House Robber', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/house-robber-ii/', 'title' => 'LeetCode #213 - House Robber II', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/longest-palindromic-substring/', 'title' => 'LeetCode #5 - Longest Palindromic Substring', 'type' => 'article'],
                    ['url' => 'https://www.amazon.com/Introduction-Algorithms-3rd-MIT-Press/dp/0262033844', 'title' => '📚 Book: Introduction to Algorithms (DP chapter)', 'type' => 'article'],
                ],
            ],
            [
                'title' => '2D Dynamic Programming',
                'description' => 'Solve 2D DP problems: unique paths, longest common subsequence.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Algorithms',
                'learning_objectives' => [],
                'skills_gained' => ['2D DP', 'DP Tables', 'State Transitions'],
                'tags' => ['dynamic-programming', '2d-dp'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://leetcode.com/problems/unique-paths/', 'title' => 'LeetCode #62 - Unique Paths', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/longest-common-subsequence/', 'title' => 'LeetCode #1143 - Longest Common Subsequence', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/edit-distance/', 'title' => 'LeetCode #72 - Edit Distance', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Advanced DP Patterns',
                'description' => 'Learn advanced DP patterns: knapsack, coin change.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Algorithms',
                'learning_objectives' => [],
                'skills_gained' => ['Knapsack', 'Advanced DP', 'DP Patterns'],
                'tags' => ['dynamic-programming', 'knapsack', 'advanced'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://leetcode.com/problems/coin-change/', 'title' => 'LeetCode #322 - Coin Change', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/partition-equal-subset-sum/', 'title' => 'LeetCode #416 - Partition Equal Subset Sum', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/target-sum/', 'title' => 'LeetCode #494 - Target Sum', 'type' => 'article'],
                ],
            ],

            // Day 26-28: Advanced Topics
            [
                'title' => 'Backtracking Algorithms',
                'description' => 'Master backtracking: permutations, combinations, subsets.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Algorithms',
                'learning_objectives' => [],
                'skills_gained' => ['Backtracking', 'Recursion', 'Constraint Solving'],
                'tags' => ['backtracking', 'recursion', 'algorithms'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=A80YzvNwqXA', 'title' => 'freeCodeCamp - Backtracking Algorithms', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/subsets/', 'title' => 'LeetCode #78 - Subsets', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/combination-sum/', 'title' => 'LeetCode #39 - Combination Sum', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/permutations/', 'title' => 'LeetCode #46 - Permutations', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Greedy Algorithms',
                'description' => 'Learn greedy algorithms and optimization techniques.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Algorithms',
                'learning_objectives' => [],
                'skills_gained' => ['Greedy Algorithms', 'Optimization', 'Algorithm Design'],
                'tags' => ['greedy', 'algorithms', 'optimization'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=bC7o8P_Ste4', 'title' => 'Abdul Bari - Greedy Algorithms', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/maximum-subarray/', 'title' => 'LeetCode #53 - Maximum Subarray', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/jump-game/', 'title' => 'LeetCode #55 - Jump Game', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/gas-station/', 'title' => 'LeetCode #134 - Gas Station', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Bit Manipulation',
                'description' => 'Master bit manipulation: bitwise operators, common bit tricks.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Algorithms',
                'learning_objectives' => [],
                'skills_gained' => ['Bit Manipulation', 'Bitwise Operators', 'Optimization'],
                'tags' => ['bit-manipulation', 'algorithms', 'optimization'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=NLKQEOgBAnw', 'title' => 'freeCodeCamp - Bit Manipulation', 'type' => 'video'],
                    ['url' => 'https://leetcode.com/problems/single-number/', 'title' => 'LeetCode #136 - Single Number', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/number-of-1-bits/', 'title' => 'LeetCode #191 - Number of 1 Bits', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/counting-bits/', 'title' => 'LeetCode #338 - Counting Bits', 'type' => 'article'],
                ],
            ],

            // Day 29-30: Practice & Interview Prep
            [
                'title' => 'Mixed Practice - Medium Problems',
                'description' => 'Practice medium-level problems combining multiple concepts.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Practice',
                'learning_objectives' => [],
                'skills_gained' => ['Problem Solving', 'Multiple Concepts', 'Time Management'],
                'tags' => ['practice', 'mixed', 'medium'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://neetcode.io/practice', 'title' => 'NeetCode Practice - Mixed Problems', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/3sum/', 'title' => 'LeetCode #15 - 3Sum', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/product-of-array-except-self/', 'title' => 'LeetCode #238 - Product of Array Except Self', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/problems/longest-increasing-subsequence/', 'title' => 'LeetCode #300 - Longest Increasing Subsequence', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Interview Preparation',
                'description' => 'Final preparation: problem-solving strategies and interview tips.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Practice',
                'learning_objectives' => [],
                'skills_gained' => ['Interview Skills', 'Time Management', 'Communication'],
                'tags' => ['interview', 'practice'],
                'success_criteria' => [],
                'has_code_submission' => false,
                'resources' => [
                    ['url' => 'https://youtube.com/watch?v=8hly31xKli0', 'title' => 'freeCodeCamp - Algorithms Interview Prep', 'type' => 'video'],
                    ['url' => 'https://neetcode.io/roadmap', 'title' => 'NeetCode 150 - Complete Roadmap', 'type' => 'article'],
                    ['url' => 'https://leetcode.com/discuss/interview-question/', 'title' => 'LeetCode - Interview Questions Discussion', 'type' => 'article'],
                ],
            ],
        ];

        $dayNumber = 1;
        foreach ($tasks as $taskData) {
            Task::create(array_merge($taskData, [
                'roadmap_id' => $roadmap->id,
                'day_number' => $dayNumber++,
                'order' => 1,
                'difficulty_level' => 'intermediate',
                'has_quality_rating' => false,
            ]));
        }
    }
}
