<?php

namespace Database\Seeders;

use App\Models\Roadmap;
use App\Models\Task;
use App\Models\User;
use Illuminate\Database\Seeder;

class BackendIntermediateRoadmapSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::where('email', 'admin@roadmap.camp')->first();

        $roadmap = Roadmap::create([
            'creator_id' => $admin->id ?? 1,
            'title' => 'Backend Intermediate',
            'description' => 'Advanced backend concepts: database optimization, caching, queues, WebSockets, API design, security, and performance.',
            'slug' => 'backend-intermediate',
            'duration_days' => 20,
            'difficulty_level' => 'advanced',
            'is_published' => true,
            'is_featured' => false,
            'order' => 6,
            'prerequisite_roadmap_id' => null,
        ]);

        $this->createTasks($roadmap);
    }

    protected function createTasks(Roadmap $roadmap): void
    {
        $tasks = [
            [
                'title' => 'Database Optimization & Indexing',
                'description' => 'Master database performance: query optimization, indexing strategies, EXPLAIN queries, and database profiling.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Database',
                'learning_objectives' => [],
                'skills_gained' => ['Database Optimization', 'Indexing', 'Query Performance', 'Database Profiling'],
                'tags' => ['database', 'optimization', 'indexing', 'performance'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://www.youtube.com/watch?v=HubezKbFL7E', 'title' => 'Database Indexing - Hussein Nasser', 'type' => 'video'],
                    ['url' => 'https://www.youtube.com/watch?v=BIlFTFrEFOI', 'title' => 'Database Sharding - Hussein Nasser', 'type' => 'video'],
                    ['url' => 'https://use-the-index-luke.com/', 'title' => 'SQL Performance Explained', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Caching Strategies & Redis',
                'description' => 'Implement caching strategies: Redis fundamentals, cache invalidation, cache-aside pattern, and Laravel caching.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['Caching', 'Redis', 'Performance Optimization', 'Cache Strategies'],
                'tags' => ['caching', 'redis', 'performance', 'optimization'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://www.youtube.com/watch?v=jgpVdJB2sKQ', 'title' => 'Redis Crash Course - Web Dev Simplified', 'type' => 'video'],
                    ['url' => 'https://www.youtube.com/watch?v=dGAgxozNWFE', 'title' => 'Caching Explained - ByteByteGo', 'type' => 'video'],
                    ['url' => 'https://laravel.com/docs/11.x/cache', 'title' => 'Laravel Cache - Laravel Docs', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Message Queues & Background Jobs',
                'description' => 'Master asynchronous processing: Laravel queues, job dispatching, workers, failed jobs, and queue monitoring.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['Message Queues', 'Background Jobs', 'Async Processing', 'Laravel Queues'],
                'tags' => ['queues', 'jobs', 'async', 'background-processing'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://www.youtube.com/watch?v=oUJbuFMyBDk', 'title' => 'Message Queues Explained - IBM Technology', 'type' => 'video'],
                    ['url' => 'https://www.youtube.com/watch?v=rXRVL0FhH6A', 'title' => 'Laravel Queues Tutorial - Code With Dary', 'type' => 'video'],
                    ['url' => 'https://laravel.com/docs/11.x/queues', 'title' => 'Laravel Queues - Laravel Docs', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'WebSockets & Real-time Communication',
                'description' => 'Implement real-time features: WebSockets, Laravel Broadcasting, Pusher, event broadcasting, and presence channels.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['WebSockets', 'Real-time Communication', 'Laravel Broadcasting', 'Event Broadcasting'],
                'tags' => ['websockets', 'realtime', 'broadcasting', 'events'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://www.youtube.com/watch?v=1BfCnjr_Vjg', 'title' => 'WebSockets Explained', 'type' => 'video'],
                    ['url' => 'https://www.youtube.com/watch?v=VJrK8S8hFxE', 'title' => 'Laravel Broadcasting - Code With Dary', 'type' => 'video'],
                    ['url' => 'https://laravel.com/docs/11.x/broadcasting', 'title' => 'Laravel Broadcasting - Laravel Docs', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Advanced API Design & Versioning',
                'description' => 'Master API design: versioning strategies, rate limiting, pagination, API resources, and error handling.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['API Design', 'API Versioning', 'Rate Limiting', 'API Best Practices'],
                'tags' => ['api', 'rest', 'design', 'best-practices'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://www.youtube.com/watch?v=lsMQRaeKNDk', 'title' => 'REST API Best Practices - ByteByteGo', 'type' => 'video'],
                    ['url' => 'https://www.youtube.com/watch?v=0oXYLzuucwE', 'title' => 'REST API Design - freeCodeCamp', 'type' => 'video'],
                    ['url' => 'https://laravel.com/docs/11.x/eloquent-resources', 'title' => 'API Resources - Laravel Docs', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'API Authentication & Security',
                'description' => 'Implement secure API authentication: JWT, Laravel Sanctum, OAuth 2.0, and API token management.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['API Authentication', 'JWT', 'OAuth', 'API Security'],
                'tags' => ['api', 'authentication', 'security', 'jwt'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://www.youtube.com/watch?v=926mknSW9Lo', 'title' => 'JWT in 100 Seconds - Fireship', 'type' => 'video'],
                    ['url' => 'https://www.youtube.com/watch?v=MT3_J2emm1w', 'title' => 'Laravel Sanctum API - Code With Dary', 'type' => 'video'],
                    ['url' => 'https://laravel.com/docs/11.x/sanctum', 'title' => 'Laravel Sanctum - Laravel Docs', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'File Uploads & Storage',
                'description' => 'Master file handling: file uploads, storage drivers, S3 integration, image processing, and file validation.',
                'estimated_time_minutes' => 90,
                'task_type' => 'video',
                'category' => 'Laravel',
                'learning_objectives' => [],
                'skills_gained' => ['File Uploads', 'Storage', 'S3', 'Image Processing'],
                'tags' => ['laravel', 'files', 'storage', 's3'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://www.youtube.com/watch?v=SEjoErbcpP4', 'title' => 'Laravel File Upload Tutorial', 'type' => 'video'],
                    ['url' => 'https://laravel.com/docs/11.x/filesystem', 'title' => 'File Storage - Laravel Docs', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Email & Notifications',
                'description' => 'Implement email sending, notification channels, mail templates, queued notifications, and SMS notifications.',
                'estimated_time_minutes' => 90,
                'task_type' => 'video',
                'category' => 'Laravel',
                'learning_objectives' => [],
                'skills_gained' => ['Email', 'Notifications', 'Mail Templates', 'SMS'],
                'tags' => ['laravel', 'email', 'notifications', 'mail'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://www.youtube.com/watch?v=F1NPG3nKxrQ', 'title' => 'Laravel Mail & Notifications Tutorial', 'type' => 'video'],
                    ['url' => 'https://laravel.com/docs/11.x/mail', 'title' => 'Mail - Laravel Docs', 'type' => 'article'],
                    ['url' => 'https://laravel.com/docs/11.x/notifications', 'title' => 'Notifications - Laravel Docs', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Testing & Test-Driven Development',
                'description' => 'Master PHPUnit testing: feature tests, unit tests, database testing, mocking, and TDD principles.',
                'estimated_time_minutes' => 120,
                'task_type' => 'video',
                'category' => 'Testing',
                'learning_objectives' => [],
                'skills_gained' => ['Testing', 'PHPUnit', 'TDD', 'Test Automation'],
                'tags' => ['testing', 'phpunit', 'tdd', 'quality'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://www.youtube.com/watch?v=aTS7nA_0YOg', 'title' => 'Laravel Testing Tutorial', 'type' => 'video'],
                    ['url' => 'https://www.youtube.com/watch?v=CZ-_rVbaBN8', 'title' => 'Laravel TDD Tutorial - Coder\'s Tape', 'type' => 'video'],
                    ['url' => 'https://laravel.com/docs/11.x/testing', 'title' => 'Testing - Laravel Docs', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Logging, Monitoring & Debugging',
                'description' => 'Implement logging, error tracking, application monitoring, performance profiling, and debugging techniques.',
                'estimated_time_minutes' => 0,
                'task_type' => 'video',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['Logging', 'Monitoring', 'Debugging', 'Error Tracking'],
                'tags' => ['logging', 'monitoring', 'debugging', 'errors'],
                'success_criteria' => [],
                'has_code_submission' => false,
                'resources' => [
                    ['url' => 'https://www.youtube.com/watch?v=l4mkEqvGWRE', 'title' => 'Laravel Telescope Tutorial - Laravel Daily', 'type' => 'video'],
                    ['url' => 'https://www.youtube.com/watch?v=SR3RzIfeozI', 'title' => 'Laravel Debugging Tutorial - Traversy Media', 'type' => 'video'],
                    ['url' => 'https://laravel.com/docs/11.x/logging', 'title' => 'Logging - Laravel Docs', 'type' => 'article'],
                    ['url' => 'https://laravel.com/docs/11.x/telescope', 'title' => 'Laravel Telescope - Laravel Docs', 'type' => 'article'],
                ],
            ],

            // Days 11-15: Payment Integration
            [
                'title' => 'Payment Integration Basics with Stripe',
                'description' => 'Learn payment gateway integration fundamentals: Stripe setup, API keys, payment intents, and basic checkout flow.',
                'estimated_time_minutes' => 120,
                'task_type' => 'exercise',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['Payment Integration', 'Stripe API', 'Payment Processing', 'Checkout Flow'],
                'tags' => ['payments', 'stripe', 'checkout', 'integration'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://www.youtube.com/watch?v=1r-F3FIONl8', 'title' => 'Stripe Payment Integration - Web Dev Simplified', 'type' => 'video'],
                    ['url' => 'https://stripe.com/docs/payments/accept-a-payment', 'title' => 'Accept a Payment - Stripe Docs', 'type' => 'article'],
                    ['url' => 'https://laravel.com/docs/11.x/billing', 'title' => 'Laravel Cashier - Laravel Docs', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Laravel Cashier & Subscription Management',
                'description' => 'Implement subscription billing with Laravel Cashier: plans, trial periods, subscription upgrades/downgrades, and cancellations.',
                'estimated_time_minutes' => 120,
                'task_type' => 'exercise',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['Subscriptions', 'Billing', 'Laravel Cashier', 'Recurring Payments'],
                'tags' => ['subscriptions', 'billing', 'cashier', 'stripe'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://laracasts.com/series/cashier-2', 'title' => 'Laravel Cashier Series - Laracasts', 'type' => 'course'],
                    ['url' => 'https://laravel.com/docs/11.x/billing', 'title' => 'Laravel Cashier Documentation', 'type' => 'article'],
                    ['url' => 'https://stripe.com/docs/billing/subscriptions/overview', 'title' => 'Stripe Subscriptions Overview', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Webhook Handling & Payment Events',
                'description' => 'Handle Stripe webhooks: payment success, failure, subscription updates, invoice events, and secure webhook verification.',
                'estimated_time_minutes' => 120,
                'task_type' => 'exercise',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['Webhooks', 'Event Handling', 'Payment Events', 'Security'],
                'tags' => ['webhooks', 'events', 'stripe', 'security'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://stripe.com/docs/webhooks', 'title' => 'Stripe Webhooks Guide', 'type' => 'article'],
                    ['url' => 'https://stripe.com/docs/webhooks/quickstart', 'title' => 'Webhooks Quick Start - Stripe', 'type' => 'tutorial'],
                    ['url' => 'https://laravel.com/docs/11.x/billing#handling-stripe-webhooks', 'title' => 'Handling Stripe Webhooks - Laravel', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Payment Security & PCI Compliance',
                'description' => 'Understand payment security best practices: PCI DSS compliance, tokenization, secure checkout, and fraud prevention.',
                'estimated_time_minutes' => 90,
                'task_type' => 'reading',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['Payment Security', 'PCI Compliance', 'Fraud Prevention', 'Tokenization'],
                'tags' => ['security', 'pci', 'compliance', 'fraud'],
                'success_criteria' => [],
                'has_code_submission' => false,
                'resources' => [
                    ['url' => 'https://stripe.com/docs/security/guide', 'title' => 'Stripe Security Guide', 'type' => 'article'],
                    ['url' => 'https://stripe.com/docs/security', 'title' => 'Security Best Practices - Stripe', 'type' => 'article'],
                    ['url' => 'https://www.pcisecuritystandards.org/document_library/', 'title' => 'PCI Security Standards Documents', 'type' => 'documentation'],
                ],
            ],
            [
                'title' => 'Multi-Currency & Payment Methods',
                'description' => 'Implement multi-currency support, different payment methods (cards, wallets, bank transfers), and currency conversion.',
                'estimated_time_minutes' => 120,
                'task_type' => 'exercise',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['Multi-Currency', 'Payment Methods', 'Currency Conversion', 'International Payments'],
                'tags' => ['multi-currency', 'payment-methods', 'international', 'conversion'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://stripe.com/docs/currencies', 'title' => 'Multi-Currency Support - Stripe', 'type' => 'article'],
                    ['url' => 'https://stripe.com/docs/payments/payment-methods/overview', 'title' => 'Payment Methods Overview - Stripe', 'type' => 'article'],
                    ['url' => 'https://stripe.com/docs/connect/currencies', 'title' => 'Currency Conversion - Stripe Connect', 'type' => 'article'],
                ],
            ],

            // Days 16-20: Advanced Backend Topics
            [
                'title' => 'Message Queues with RabbitMQ/Redis',
                'description' => 'Advanced queue systems: RabbitMQ setup, queue workers, job prioritization, queue monitoring, and failure handling.',
                'estimated_time_minutes' => 120,
                'task_type' => 'exercise',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['RabbitMQ', 'Message Queues', 'Queue Management', 'Job Processing'],
                'tags' => ['rabbitmq', 'queues', 'redis', 'messaging'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://www.youtube.com/watch?v=deG25y_r6OY', 'title' => 'RabbitMQ in 5 Minutes', 'type' => 'video'],
                    ['url' => 'https://www.rabbitmq.com/tutorials/tutorial-one-php.html', 'title' => 'RabbitMQ Tutorial - PHP', 'type' => 'article'],
                    ['url' => 'https://laravel.com/docs/11.x/queues#rabbitmq', 'title' => 'Laravel RabbitMQ Setup', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Advanced Caching Patterns',
                'description' => 'Master advanced caching: cache warming, distributed caching, cache stampede prevention, and cache tags.',
                'estimated_time_minutes' => 120,
                'task_type' => 'exercise',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['Advanced Caching', 'Distributed Cache', 'Cache Patterns', 'Performance'],
                'tags' => ['caching', 'redis', 'performance', 'optimization'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://www.youtube.com/watch?v=6FyXURRVmR0', 'title' => 'Advanced Caching Strategies', 'type' => 'video'],
                    ['url' => 'https://redis.io/docs/latest/develop/use/patterns/', 'title' => 'Redis Patterns', 'type' => 'article'],
                    ['url' => 'https://laravel.com/docs/11.x/cache#cache-tags', 'title' => 'Cache Tags - Laravel', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Cloud Storage & CDN Integration',
                'description' => 'Implement cloud storage: AWS S3, DigitalOcean Spaces, CDN integration, image optimization, and asset management.',
                'estimated_time_minutes' => 120,
                'task_type' => 'exercise',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['Cloud Storage', 'AWS S3', 'CDN', 'Asset Management'],
                'tags' => ['cloud', 's3', 'cdn', 'storage'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://www.youtube.com/watch?v=tfU0JEZjcsg', 'title' => 'AWS S3 Tutorial', 'type' => 'video'],
                    ['url' => 'https://laravel.com/docs/11.x/filesystem#amazon-s3-compatible-filesystems', 'title' => 'S3 Integration - Laravel', 'type' => 'article'],
                    ['url' => 'https://aws.amazon.com/s3/getting-started/', 'title' => 'Getting Started with S3 - AWS', 'type' => 'article'],
                ],
            ],
            [
                'title' => 'Advanced Email & Notification Systems',
                'description' => 'Build advanced notification systems: email queuing, notification preferences, multi-channel notifications, and analytics.',
                'estimated_time_minutes' => 120,
                'task_type' => 'exercise',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['Email Systems', 'Notification Management', 'Multi-Channel', 'Email Analytics'],
                'tags' => ['email', 'notifications', 'queues', 'analytics'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://laravel.com/docs/11.x/notifications', 'title' => 'Laravel Notifications Documentation', 'type' => 'article'],
                    ['url' => 'https://laravel.com/docs/11.x/mail', 'title' => 'Laravel Mail Documentation', 'type' => 'article'],
                    ['url' => 'https://laracasts.com/series/laravel-8-from-scratch/episodes/62', 'title' => 'Notifications - Laracasts', 'type' => 'video'],
                ],
            ],
            [
                'title' => 'API Rate Limiting & Throttling',
                'description' => 'Implement advanced rate limiting: custom throttle strategies, rate limit headers, distributed rate limiting, and bypass mechanisms.',
                'estimated_time_minutes' => 120,
                'task_type' => 'exercise',
                'category' => 'Backend',
                'learning_objectives' => [],
                'skills_gained' => ['Rate Limiting', 'Throttling', 'API Security', 'Performance'],
                'tags' => ['rate-limiting', 'throttling', 'api', 'security'],
                'success_criteria' => [],
                'has_code_submission' => true,
                'resources' => [
                    ['url' => 'https://www.youtube.com/watch?v=FU4WlwfS3G0', 'title' => 'Rate Limiting Explained - ByteByteGo', 'type' => 'video'],
                    ['url' => 'https://laravel.com/docs/11.x/routing#rate-limiting', 'title' => 'Rate Limiting - Laravel', 'type' => 'article'],
                    ['url' => 'https://redis.io/glossary/rate-limiting/', 'title' => 'Rate Limiting with Redis', 'type' => 'article'],
                ],
            ],
        ];

        $dayNumber = 1;
        foreach ($tasks as $taskData) {
            Task::create(array_merge($taskData, [
                'roadmap_id' => $roadmap->id,
                'day_number' => $dayNumber++,
                'order' => 1,
                'difficulty_level' => 'advanced',
                'has_quality_rating' => true,
            ]));
        }
    }
}
