<?php

namespace App\Livewire\Student;

use Livewire\Component;

class Newsletters extends Component
{
    public $newsletters = [];

    public function mount()
    {
        $this->newsletters = [
            // English Newsletters
            [
                'name' => 'JavaScript Weekly',
                'url' => 'https://javascriptweekly.com',
                'description' => 'A free, once–weekly email roundup of JavaScript news and articles. The most popular JavaScript newsletter with over 175,000 subscribers.',
                'topics' => ['JavaScript', 'News', 'Articles', 'Community'],
                'frequency' => 'Weekly',
                'subscribers' => '175K+',
                'icon' => '📰',
                'language' => 'en',
            ],
            [
                'name' => 'Node Weekly',
                'url' => 'https://nodeweekly.com',
                'description' => 'A free, once–weekly email roundup of Node.js news and articles. Essential reading for Node.js developers and backend JavaScript enthusiasts.',
                'topics' => ['Node.js', 'Backend', 'JavaScript', 'Server-Side'],
                'frequency' => 'Weekly',
                'subscribers' => '50K+',
                'icon' => '📮',
                'language' => 'en',
            ],
            [
                'name' => 'React Status',
                'url' => 'https://react.statuscode.com',
                'description' => 'A weekly roundup of the latest React and React Native links and tutorials. Curated news, articles, and releases for React developers.',
                'topics' => ['React', 'React Native', 'Frontend', 'JavaScript'],
                'frequency' => 'Weekly',
                'subscribers' => '70K+',
                'icon' => '⚛️',
                'language' => 'en',
            ],
            [
                'name' => 'Frontend Focus',
                'url' => 'https://frontendfoc.us',
                'description' => 'A once–weekly roundup of the best frontend news, articles and tutorials. HTML, CSS, WebGL, Canvas, browser tech, and more.',
                'topics' => ['Frontend', 'HTML', 'CSS', 'WebGL', 'Browser'],
                'frequency' => 'Weekly',
                'subscribers' => '55K+',
                'icon' => '🎨',
                'language' => 'en',
            ],
            [
                'name' => 'CSS Weekly',
                'url' => 'https://css-weekly.com',
                'description' => 'Weekly email roundup of CSS articles, tutorials, experiments and tools curated by Zoran Jambor. Perfect for staying current with CSS.',
                'topics' => ['CSS', 'Design', 'Frontend', 'Web Development'],
                'frequency' => 'Weekly',
                'subscribers' => '35K+',
                'icon' => '💅',
                'language' => 'en',
            ],
            [
                'name' => 'Laravel News',
                'url' => 'https://laravel-news.com/newsletter',
                'description' => 'Every week we send out a newsletter with updates from the Laravel ecosystem. News, packages, tutorials, and more.',
                'topics' => ['Laravel', 'PHP', 'Backend', 'Web Development'],
                'frequency' => 'Weekly',
                'subscribers' => '40K+',
                'icon' => '🔴',
                'language' => 'en',
            ],
            [
                'name' => 'PHP Weekly',
                'url' => 'http://www.phpweekly.com',
                'description' => 'A free once-a-week newsletter about PHP, featuring articles, news, and blog posts. Essential for PHP developers.',
                'topics' => ['PHP', 'Backend', 'Web Development', 'Programming'],
                'frequency' => 'Weekly',
                'subscribers' => '25K+',
                'icon' => '🐘',
                'language' => 'en',
            ],
            [
                'name' => 'Postgres Weekly',
                'url' => 'https://postgresweekly.com',
                'description' => 'A free, once–weekly email roundup of PostgreSQL news and articles. Great for database administrators and backend developers.',
                'topics' => ['PostgreSQL', 'Databases', 'SQL', 'Backend'],
                'frequency' => 'Weekly',
                'subscribers' => '20K+',
                'icon' => '🐘',
                'language' => 'en',
            ],
            [
                'name' => 'Go Weekly',
                'url' => 'https://golangweekly.com',
                'description' => 'A weekly newsletter about the Go programming language. News, articles, projects, and updates from the Go community.',
                'topics' => ['Go', 'Golang', 'Backend', 'Systems Programming'],
                'frequency' => 'Weekly',
                'subscribers' => '30K+',
                'icon' => '🔵',
                'language' => 'en',
            ],
            [
                'name' => 'Python Weekly',
                'url' => 'https://pythonweekly.com',
                'description' => 'A free weekly newsletter featuring curated news, articles, new releases, jobs and more for Python developers.',
                'topics' => ['Python', 'Data Science', 'Web Development', 'AI/ML'],
                'frequency' => 'Weekly',
                'subscribers' => '45K+',
                'icon' => '🐍',
                'language' => 'en',
            ],
            [
                'name' => 'Ruby Weekly',
                'url' => 'https://rubyweekly.com',
                'description' => 'A free, once–weekly email roundup of Ruby news and articles. Essential for Ruby and Rails developers.',
                'topics' => ['Ruby', 'Rails', 'Web Development', 'Backend'],
                'frequency' => 'Weekly',
                'subscribers' => '30K+',
                'icon' => '💎',
                'language' => 'en',
            ],
            [
                'name' => 'DevOps Weekly',
                'url' => 'https://devopsweekly.com',
                'description' => 'A weekly slice of DevOps news. Tools, tutorials, culture, and more. Perfect for DevOps engineers and SREs.',
                'topics' => ['DevOps', 'Infrastructure', 'Cloud', 'Automation'],
                'frequency' => 'Weekly',
                'subscribers' => '35K+',
                'icon' => '⚙️',
                'language' => 'en',
            ],
            [
                'name' => 'Kubernetes Weekly',
                'url' => 'https://kubeweekly.io',
                'description' => 'Weekly newsletter about Kubernetes and cloud-native technologies. Curated news, tutorials, and updates.',
                'topics' => ['Kubernetes', 'Cloud Native', 'Containers', 'DevOps'],
                'frequency' => 'Weekly',
                'subscribers' => '15K+',
                'icon' => '☸️',
                'language' => 'en',
            ],
            [
                'name' => 'Bytes',
                'url' => 'https://bytes.dev',
                'description' => 'The JavaScript newsletter that keeps you informed without taking up too much of your time. Fun, educational, and informative.',
                'topics' => ['JavaScript', 'Frontend', 'Web Development', 'News'],
                'frequency' => 'Weekly',
                'subscribers' => '100K+',
                'icon' => '🎯',
                'language' => 'en',
            ],
            [
                'name' => 'TLDR Newsletter',
                'url' => 'https://tldr.tech',
                'description' => 'Daily newsletter with links and TLDRs of the most interesting stories in tech, science, and coding. Quick reads for busy developers.',
                'topics' => ['Technology', 'Programming', 'News', 'Science'],
                'frequency' => 'Daily',
                'subscribers' => '1M+',
                'icon' => '📬',
                'language' => 'en',
            ],
            [
                'name' => 'The Pragmatic Engineer',
                'url' => 'https://newsletter.pragmaticengineer.com',
                'description' => 'Weekly newsletter on engineering, tech, and software development leadership by Gergely Orosz. Deep dives into tech companies and engineering culture.',
                'topics' => ['Engineering', 'Leadership', 'Career', 'Tech Companies'],
                'frequency' => 'Weekly',
                'subscribers' => '250K+',
                'icon' => '💼',
                'language' => 'en',
            ],
            [
                'name' => 'Pointer',
                'url' => 'https://pointer.io',
                'description' => 'A reading club for software developers. Curated articles about software development, engineering culture, and technology.',
                'topics' => ['Software Development', 'Engineering', 'Culture', 'Best Practices'],
                'frequency' => 'Weekly',
                'subscribers' => '20K+',
                'icon' => '👆',
                'language' => 'en',
            ],
            [
                'name' => 'Stefan\'s Web Weekly',
                'url' => 'https://stefan-judis.com/newsletter',
                'description' => 'Weekly web development newsletter. Web platform news, CSS, JavaScript, and developer tools.',
                'topics' => ['Web Development', 'CSS', 'JavaScript', 'Web Platform'],
                'frequency' => 'Weekly',
                'subscribers' => '10K+',
                'icon' => '🌐',
                'language' => 'en',
            ],
            [
                'name' => 'Console',
                'url' => 'https://console.dev',
                'description' => 'A free weekly email digest of the best tools and beta releases for developers. Discover new developer tools.',
                'topics' => ['Developer Tools', 'Open Source', 'Products', 'Beta'],
                'frequency' => 'Weekly',
                'subscribers' => '15K+',
                'icon' => '🛠️',
                'language' => 'en',
            ],
            [
                'name' => 'Awesome',
                'url' => 'https://awesome.re/newsletter',
                'description' => 'Weekly newsletter about awesome lists. Curated lists about all kinds of interesting topics in tech.',
                'topics' => ['Curated Lists', 'Resources', 'Learning', 'Tools'],
                'frequency' => 'Weekly',
                'subscribers' => '8K+',
                'icon' => '⭐',
                'language' => 'en',
            ],
            [
                'name' => 'Hacker Newsletter',
                'url' => 'https://hackernewsletter.com',
                'description' => 'A weekly newsletter of the best articles on startups, technology, programming, and more from Hacker News.',
                'topics' => ['Startups', 'Technology', 'Programming', 'Business'],
                'frequency' => 'Weekly',
                'subscribers' => '60K+',
                'icon' => '📡',
                'language' => 'en',
            ],
            [
                'name' => 'StatusCode',
                'url' => 'https://weekly.statuscode.com',
                'description' => 'A weekly newsletter covering software development, web operations, and devops. Curated links and news.',
                'topics' => ['Software Development', 'DevOps', 'Operations', 'News'],
                'frequency' => 'Weekly',
                'subscribers' => '25K+',
                'icon' => '📊',
                'language' => 'en',
            ],
            [
                'name' => 'Sidebar',
                'url' => 'https://sidebar.io',
                'description' => 'Five design links, every weekday. The best design articles, inspiration and resources delivered to your inbox.',
                'topics' => ['Design', 'UI/UX', 'Web Design', 'Inspiration'],
                'frequency' => 'Daily',
                'subscribers' => '40K+',
                'icon' => '🎨',
                'language' => 'en',
            ],
            [
                'name' => 'Software Lead Weekly',
                'url' => 'https://softwareleadweekly.com',
                'description' => 'A weekly email for busy people who care about people, culture and leadership. Perfect for tech leads and managers.',
                'topics' => ['Leadership', 'Management', 'Culture', 'Teams'],
                'frequency' => 'Weekly',
                'subscribers' => '12K+',
                'icon' => '👔',
                'language' => 'en',
            ],
            [
                'name' => 'rendezvous with cassidoo',
                'url' => 'https://cassidoo.co/newsletter',
                'description' => 'Weekly newsletter about tech, career advice, and fun coding interview questions by Cassidy Williams.',
                'topics' => ['Career', 'Interview Prep', 'Technology', 'Coding'],
                'frequency' => 'Weekly',
                'subscribers' => '30K+',
                'icon' => '💌',
                'language' => 'en',
            ],
            [
                'name' => 'Cooperpress Newsletters',
                'url' => 'https://cooperpress.com/publications',
                'description' => 'Publisher of numerous programming language and technology newsletters including JavaScript, Node, Frontend, and more.',
                'topics' => ['Multiple Topics', 'Programming', 'Technology', 'News'],
                'frequency' => 'Various',
                'subscribers' => '500K+ Total',
                'icon' => '📚',
                'language' => 'en',
            ],
        ];
    }

    public function render()
    {
        return view('livewire.student.newsletters');
    }
}
