<?php

namespace App\Livewire\Student;

use Livewire\Component;

class Podcasts extends Component
{
    public $podcasts = [];

    public function mount()
    {
        $this->podcasts = [
            // English Podcasts
            [
                'name' => 'Syntax',
                'url' => 'https://syntax.fm',
                'description' => 'A Tasty Treats Podcast for Web Developers by Wes Bos and Scott Tolinski. Covers web development topics, JavaScript frameworks, CSS, tooling, and career advice with a fun and casual approach.',
                'topics' => ['Web Development', 'JavaScript', 'React', 'CSS', 'Career'],
                'hosts' => 'Wes Bos & Scott Tolinski',
                'frequency' => '3x per week',
                'icon' => '🎙️',
                'language' => 'en',
            ],
            [
                'name' => 'The Changelog',
                'url' => 'https://changelog.com/podcast',
                'description' => 'Conversations with the hackers, leaders, and innovators of the software world. Deep dives into open source projects, programming languages, and the people behind them.',
                'topics' => ['Open Source', 'Programming', 'Tech News', 'Interviews'],
                'hosts' => 'Adam Stacoviak & Jerod Santo',
                'frequency' => 'Weekly',
                'icon' => '📻',
                'language' => 'en',
            ],
            [
                'name' => 'Software Engineering Daily',
                'url' => 'https://softwareengineeringdaily.com',
                'description' => 'Daily interviews about technical software topics, covering databases, cloud infrastructure, distributed systems, machine learning, and emerging technologies.',
                'topics' => ['Software Engineering', 'Cloud', 'Databases', 'Architecture'],
                'hosts' => 'Various Hosts',
                'frequency' => 'Daily',
                'icon' => '🎧',
                'language' => 'en',
            ],
            [
                'name' => 'Full Stack Radio',
                'url' => 'https://fullstackradio.com',
                'description' => 'A podcast for developers interested in building great software products. Hosted by Adam Wathan, creator of Tailwind CSS. Topics include product design, development, and business.',
                'topics' => ['Full Stack', 'Product Development', 'Business', 'Design'],
                'hosts' => 'Adam Wathan',
                'frequency' => 'Bi-weekly',
                'icon' => '📡',
                'language' => 'en',
            ],
            [
                'name' => 'Shop Talk Show',
                'url' => 'https://shoptalkshow.com',
                'description' => 'A podcast about front-end web design and development. Weekly discussion of CSS, JavaScript, accessibility, performance, and all things web.',
                'topics' => ['Frontend', 'CSS', 'JavaScript', 'Web Design'],
                'hosts' => 'Chris Coyier & Dave Rupert',
                'frequency' => 'Weekly',
                'icon' => '💬',
                'language' => 'en',
            ],
            [
                'name' => 'JS Party',
                'url' => 'https://changelog.com/jsparty',
                'description' => 'A community celebration of JavaScript and the web. Weekly episodes about JavaScript, web platform, Node.js, and the latest trends in the JS ecosystem.',
                'topics' => ['JavaScript', 'Node.js', 'Web Platform', 'Community'],
                'hosts' => 'Various Panelists',
                'frequency' => 'Weekly',
                'icon' => '🎉',
                'language' => 'en',
            ],
            [
                'name' => 'CodeNewbie',
                'url' => 'https://codenewbie.org/podcast',
                'description' => 'Stories from people on their coding journey. Perfect for beginners and career changers learning to code. Inspiring interviews with developers at all levels.',
                'topics' => ['Learning to Code', 'Career Change', 'Beginners', 'Inspiration'],
                'hosts' => 'Saron Yitbarek',
                'frequency' => 'Weekly',
                'icon' => '🌱',
                'language' => 'en',
            ],
            [
                'name' => 'Developer Tea',
                'url' => 'https://developertea.com',
                'description' => 'Short, focused episodes designed to fit inside your tea break. Covers career development, productivity, and becoming a better developer.',
                'topics' => ['Career Development', 'Productivity', 'Soft Skills', 'Mindset'],
                'hosts' => 'Jonathan Cutrell',
                'frequency' => '3x per week',
                'icon' => '☕',
                'language' => 'en',
            ],
            [
                'name' => 'React Podcast',
                'url' => 'https://reactpodcast.com',
                'description' => 'Conversations about React with your favorite developers. Deep dives into React, React Native, GraphQL, and the ecosystem surrounding modern JavaScript.',
                'topics' => ['React', 'React Native', 'GraphQL', 'JavaScript'],
                'hosts' => 'Michael Chan',
                'frequency' => 'Bi-weekly',
                'icon' => '⚛️',
                'language' => 'en',
            ],
            [
                'name' => 'The Laravel Podcast',
                'url' => 'https://laravelpodcast.com',
                'description' => 'The official Laravel podcast. Discussions about Laravel, PHP, and related web development topics with members of the Laravel community.',
                'topics' => ['Laravel', 'PHP', 'Web Development', 'Community'],
                'hosts' => 'Matt Stauffer & Various',
                'frequency' => 'Weekly',
                'icon' => '🔴',
                'language' => 'en',
            ],
            [
                'name' => 'Darknet Diaries',
                'url' => 'https://darknetdiaries.com',
                'description' => 'True stories from the dark side of the Internet. Hackers, breaches, cybercrime, and all the things that dwell on the hidden parts of the network.',
                'topics' => ['Cybersecurity', 'Hacking', 'True Stories', 'Privacy'],
                'hosts' => 'Jack Rhysider',
                'frequency' => 'Bi-weekly',
                'icon' => '🕵️',
                'language' => 'en',
            ],
            [
                'name' => 'Talk Python To Me',
                'url' => 'https://talkpython.fm',
                'description' => 'A podcast on Python and related technologies. Interviews with Python developers, discussions on Python frameworks, data science, and web development.',
                'topics' => ['Python', 'Data Science', 'Web Development', 'Machine Learning'],
                'hosts' => 'Michael Kennedy',
                'frequency' => 'Weekly',
                'icon' => '🐍',
                'language' => 'en',
            ],
            [
                'name' => 'The Stack Overflow Podcast',
                'url' => 'https://stackoverflow.blog/podcast',
                'description' => 'The home for Stack Overflow\'s podcast. Conversations with fascinating guests about how technology is made and where it\'s headed.',
                'topics' => ['Technology', 'Programming', 'Community', 'Careers'],
                'hosts' => 'Ben Popper & Various',
                'frequency' => 'Weekly',
                'icon' => '💻',
                'language' => 'en',
            ],
            [
                'name' => 'Hanselminutes',
                'url' => 'https://hanselminutes.com',
                'description' => 'Fresh Air for Developers. Scott Hanselman interviews developers, designers, and technologists on a wide variety of topics.',
                'topics' => ['Technology', 'Software', 'Innovation', 'Interviews'],
                'hosts' => 'Scott Hanselman',
                'frequency' => 'Weekly',
                'icon' => '🎤',
                'language' => 'en',
            ],
            [
                'name' => 'Coding Blocks',
                'url' => 'https://codingblocks.net',
                'description' => 'Podcast and website dedicated to learning how to become a better software developer. Deep dives into algorithms, design patterns, and best practices.',
                'topics' => ['Algorithms', 'Design Patterns', 'Clean Code', 'Best Practices'],
                'hosts' => 'Allen Underwood, Michael Outlaw & Joe Zack',
                'frequency' => 'Bi-weekly',
                'icon' => '🧱',
                'language' => 'en',
            ],
            [
                'name' => 'The Real Python Podcast',
                'url' => 'https://realpython.com/podcasts/rpp',
                'description' => 'A weekly Python podcast with interviews, coding tips, and conversation with guests from the Python community.',
                'topics' => ['Python', 'Programming', 'Community', 'Tips'],
                'hosts' => 'Christopher Bailey',
                'frequency' => 'Weekly',
                'icon' => '🎯',
                'language' => 'en',
            ],
            [
                'name' => 'Base.cs Podcast',
                'url' => 'https://www.codenewbie.org/basecs',
                'description' => 'Beginner-friendly computer science lessons based on Vaidehi Joshi\'s base.cs blog series. Perfect for understanding CS fundamentals.',
                'topics' => ['Computer Science', 'Algorithms', 'Data Structures', 'Beginners'],
                'hosts' => 'Vaidehi Joshi & Saron Yitbarek',
                'frequency' => 'Seasonal',
                'icon' => '📚',
                'language' => 'en',
            ],
            [
                'name' => 'The freeCodeCamp Podcast',
                'url' => 'https://freecodecamp.org/news/tag/podcast',
                'description' => 'Stories from people who are learning to code. Interviews with developers, advice on learning programming, and technology discussions.',
                'topics' => ['Learning to Code', 'Career', 'Technology', 'Education'],
                'hosts' => 'Quincy Larson',
                'frequency' => 'Weekly',
                'icon' => '🎓',
                'language' => 'en',
            ],
            [
                'name' => 'Command Line Heroes',
                'url' => 'https://redhat.com/en/command-line-heroes',
                'description' => 'An original podcast about the people who transform technology from the command line up. Stories from open source, DevOps, and cloud computing.',
                'topics' => ['Open Source', 'DevOps', 'Cloud', 'Technology History'],
                'hosts' => 'Saron Yitbarek',
                'frequency' => 'Seasonal',
                'icon' => '⌨️',
                'language' => 'en',
            ],
            [
                'name' => 'Adventures in DevOps',
                'url' => 'https://topenddevs.com/podcasts/adventures-in-devops',
                'description' => 'Weekly podcast about DevOps, cloud infrastructure, containers, Kubernetes, CI/CD, and modern deployment practices.',
                'topics' => ['DevOps', 'Cloud', 'Kubernetes', 'CI/CD'],
                'hosts' => 'Various Hosts',
                'frequency' => 'Weekly',
                'icon' => '🚀',
                'language' => 'en',
            ],
        ];
    }

    public function render()
    {
        return view('livewire.student.podcasts');
    }
}
