<?php

namespace App\Livewire\Student;

use Livewire\Component;

class YoutubeChannels extends Component
{
    public $channels = [];

    public function mount()
    {
        $this->channels = [
            // English Channels
            [
                'name' => 'freeCodeCamp',
                'url' => 'https://www.youtube.com/@freecodecamp',
                'description' => 'Comprehensive programming tutorials and full courses',
                'topics' => ['Full Stack', 'Web Development', 'Python', 'JavaScript', 'Computer Science'],
                'icon' => '🎓',
                'language' => 'en',
            ],
            [
                'name' => 'Traversy Media',
                'url' => 'https://www.youtube.com/@TraversyMedia',
                'description' => 'Comprehensive web development tutorials covering modern technologies',
                'topics' => ['JavaScript', 'React', 'Node.js', 'Full Stack', 'Web Development'],
                'icon' => '🚀',
                'language' => 'en',
            ],
            [
                'name' => 'CS Dojo',
                'url' => 'https://www.youtube.com/@CSDojo',
                'description' => 'Programming fundamentals and career guidance',
                'topics' => ['Python', 'Programming Basics', 'Data Structures', 'Career Advice'],
                'icon' => '💻',
                'language' => 'en',
            ],
            [
                'name' => 'The Net Ninja',
                'url' => 'https://www.youtube.com/@NetNinja',
                'description' => 'Web development tutorials, modern JavaScript frameworks and more',
                'topics' => ['JavaScript', 'React', 'Vue', 'Firebase', 'Node.js'],
                'icon' => '🥷',
                'language' => 'en',
            ],
            [
                'name' => 'Web Dev Simplified',
                'url' => 'https://www.youtube.com/@WebDevSimplified',
                'description' => 'Web development made simple with practical tutorials',
                'topics' => ['JavaScript', 'React', 'CSS', 'Web Development'],
                'icon' => '⚡',
                'language' => 'en',
            ],
            [
                'name' => 'Fireship',
                'url' => 'https://www.youtube.com/@Fireship',
                'description' => 'High-intensity code tutorials and tech explanations',
                'topics' => ['JavaScript', 'Firebase', 'Web Development', 'Tech News'],
                'icon' => '🔥',
                'language' => 'en',
            ],
            [
                'name' => 'Kevin Powell',
                'url' => 'https://www.youtube.com/@KevinPowell',
                'description' => 'CSS expert teaching modern CSS techniques and best practices',
                'topics' => ['CSS', 'Frontend', 'Web Design', 'Responsive Design'],
                'icon' => '🎨',
                'language' => 'en',
            ],
            [
                'name' => 'Academind',
                'url' => 'https://www.youtube.com/@academind',
                'description' => 'Comprehensive courses on web development and programming',
                'topics' => ['React', 'Angular', 'Vue', 'Node.js', 'Full Stack'],
                'icon' => '📚',
                'language' => 'en',
            ],
            [
                'name' => 'Tech With Tim',
                'url' => 'https://www.youtube.com/@TechWithTim',
                'description' => 'Python programming, machine learning, and game development',
                'topics' => ['Python', 'Machine Learning', 'Game Development', 'AI'],
                'icon' => '🐍',
                'language' => 'en',
            ],
            [
                'name' => 'Programming with Mosh',
                'url' => 'https://www.youtube.com/@programmingwithmosh',
                'description' => 'Professional programming tutorials for beginners and experts',
                'topics' => ['Python', 'JavaScript', 'C#', 'Java', 'Programming'],
                'icon' => '👨‍🏫',
                'language' => 'en',
            ],
            [
                'name' => 'Corey Schafer',
                'url' => 'https://www.youtube.com/@coreyms',
                'description' => 'Python programming tutorials and development tips',
                'topics' => ['Python', 'Django', 'Flask', 'Data Science'],
                'icon' => '🔬',
                'language' => 'en',
            ],
            [
                'name' => 'Ben Awad',
                'url' => 'https://www.youtube.com/@bawad',
                'description' => 'Full-stack development with React, GraphQL, and TypeScript',
                'topics' => ['React', 'GraphQL', 'TypeScript', 'Full Stack'],
                'icon' => '⚛️',
                'language' => 'en',
            ],
            [
                'name' => 'Hussein Nasser',
                'url' => 'https://www.youtube.com/@hnasr',
                'description' => 'Backend engineering, databases, and system design',
                'topics' => ['Backend', 'Databases', 'System Design', 'Networking'],
                'icon' => '🗄️',
                'language' => 'en',
            ],
            [
                'name' => 'ByteByteGo',
                'url' => 'https://www.youtube.com/@ByteByteGo',
                'description' => 'System design and software architecture explained visually',
                'topics' => ['System Design', 'Architecture', 'Distributed Systems'],
                'icon' => '📊',
                'language' => 'en',
            ],
            [
                'name' => 'NeetCode',
                'url' => 'https://www.youtube.com/@NeetCode',
                'description' => 'Coding interview preparation and LeetCode solutions',
                'topics' => ['Algorithms', 'Data Structures', 'Interview Prep', 'LeetCode'],
                'icon' => '🧩',
                'language' => 'en',
            ],
            [
                'name' => 'Theo - t3.gg',
                'url' => 'https://www.youtube.com/@t3dotgg',
                'description' => 'Modern web development, TypeScript, and tech discussions',
                'topics' => ['TypeScript', 'React', 'Next.js', 'Web Development'],
                'icon' => '🎯',
                'language' => 'en',
            ],
            [
                'name' => 'ThePrimeagen',
                'url' => 'https://www.youtube.com/@ThePrimeagen',
                'description' => 'Vim, algorithms, and software engineering entertainment',
                'topics' => ['Vim', 'Algorithms', 'Programming', 'Software Engineering'],
                'icon' => '⚔️',
                'language' => 'en',
            ],
            [
                'name' => 'DesignCourse',
                'url' => 'https://www.youtube.com/@DesignCourse',
                'description' => 'UI/UX design and frontend development',
                'topics' => ['UI/UX', 'Design', 'Frontend', 'Figma'],
                'icon' => '🎨',
                'language' => 'en',
            ],

            // Arabic Channels
            [
                'name' => 'Coders Camp - رشا عبدين',
                'name_en' => 'Coders Camp - Rasha Abdeen',
                'url' => 'https://www.youtube.com/@coderscamp-rashaabdeen2865',
                'description_ar' => 'قناة متخصصة في تعليم البرمجة باللغة العربية، تركز على Laravel و PHP',
                'description_en' => 'Specialized in programming education in Arabic, focusing on Laravel & PHP',
                'topics' => ['Laravel', 'PHP', 'Backend Development'],
                'icon' => '🎓',
                'language' => 'ar',
            ],
            [
                'name' => 'Elzero Web School',
                'name_en' => 'Elzero Web School',
                'url' => 'https://www.youtube.com/@ElzeroWebSchool',
                'description_ar' => 'من أشهر القنوات العربية لتعليم البرمجة، تقدم دورات شاملة في HTML, CSS, JavaScript, PHP',
                'description_en' => 'One of the most famous Arabic programming channels, offering comprehensive courses',
                'topics' => ['HTML', 'CSS', 'JavaScript', 'PHP', 'Python'],
                'icon' => '🌟',
                'language' => 'ar',
            ],
            [
                'name' => 'Firefox Egy Web',
                'name_en' => 'Firefox Egy Web',
                'url' => 'https://www.youtube.com/@firefoxegyweb',
                'description_ar' => 'قناة متخصصة في تطوير الويب والبرمجة',
                'description_en' => 'Specialized in web development and programming',
                'topics' => ['Web Development', 'Frontend', 'Backend'],
                'icon' => '🦊',
                'language' => 'ar',
            ],
            [
                'name' => 'Arabic Competitive Programming',
                'name_en' => 'Arabic Competitive Programming',
                'url' => 'https://www.youtube.com/@ArabicCompetitiveProgramming',
                'description_ar' => 'تعليم البرمجة التنافسية والخوارزميات وحل المشكلات',
                'description_en' => 'Teaching competitive programming, algorithms and problem solving',
                'topics' => ['Algorithms', 'Data Structures', 'Problem Solving'],
                'icon' => '🏆',
                'language' => 'ar',
            ],
            [
                'name' => 'Desouki Egypt',
                'name_en' => 'Desouki Egypt',
                'url' => 'https://www.youtube.com/@DesoukiEgypt',
                'description_ar' => 'دورات برمجية متنوعة',
                'description_en' => 'Various programming courses',
                'topics' => ['Programming', 'Software Development'],
                'icon' => '💻',
                'language' => 'ar',
            ],
            [
                'name' => 'Big Data',
                'name_en' => 'Big Data',
                'url' => 'https://www.youtube.com/@bigdata4756',
                'description_ar' => 'قناة متخصصة في البيانات الضخمة وعلوم البيانات',
                'description_en' => 'Specialized in Big Data and Data Science',
                'topics' => ['Big Data', 'Data Science', 'Algorithms'],
                'icon' => '📊',
                'language' => 'ar',
            ],
            [
                'name' => 'Sec Theater',
                'name_en' => 'Sec Theater',
                'url' => 'https://www.youtube.com/@SecTheater',
                'description_ar' => 'تعليم أمن المعلومات والاختراق الأخلاقي',
                'description_en' => 'Teaching cybersecurity and ethical hacking',
                'topics' => ['Cybersecurity', 'Ethical Hacking', 'Security'],
                'icon' => '🔒',
                'language' => 'ar',
            ],
            [
                'name' => 'Ameer Gaafar',
                'name_en' => 'Ameer Gaafar',
                'url' => 'https://www.youtube.com/@AmeerGaafar',
                'description_ar' => 'محتوى برمجي متنوع',
                'description_en' => 'Various programming content',
                'topics' => ['Programming', 'Web Development'],
                'icon' => '👨‍💻',
                'language' => 'ar',
            ],
            [
                'name' => 'Tariq El Ouzeh',
                'name_en' => 'Tariq El Ouzeh',
                'url' => 'https://www.youtube.com/@tariqelouzeh',
                'description_ar' => 'تعليم البرمجة والتطوير',
                'description_en' => 'Teaching programming and development',
                'topics' => ['Programming', 'Development'],
                'icon' => '🎯',
                'language' => 'ar',
            ],
            [
                'name' => 'Adel Nasim',
                'name_en' => 'Adel Nasim',
                'url' => 'https://www.youtube.com/@AdelNasim',
                'description_ar' => 'محتوى تعليمي في البرمجة',
                'description_en' => 'Educational programming content',
                'topics' => ['Programming', 'Software Engineering'],
                'icon' => '📚',
                'language' => 'ar',
            ],
            [
                'name' => 'Dr. Mohammed El Said',
                'name_en' => 'Dr. Mohammed El Said',
                'url' => 'https://www.youtube.com/@DrMohammedElSaid',
                'description_ar' => 'دورات أكاديمية في علوم الحاسب',
                'description_en' => 'Academic courses in computer science',
                'topics' => ['Computer Science', 'Programming'],
                'icon' => '🎓',
                'language' => 'ar',
            ],
            [
                'name' => 'Passionate Coders',
                'name_en' => 'Passionate Coders',
                'url' => 'https://www.youtube.com/@PassionateCoders',
                'description_ar' => 'شغوفون بالبرمجة',
                'description_en' => 'Passionate about coding',
                'topics' => ['Programming', 'Web Development'],
                'icon' => '❤️',
                'language' => 'ar',
            ],
            [
                'name' => 'Pragma AR',
                'name_en' => 'Pragma AR',
                'url' => 'https://www.youtube.com/@pragma-ar',
                'description_ar' => 'محتوى برمجي باللغة العربية',
                'description_en' => 'Programming content in Arabic',
                'topics' => ['Programming', 'Software Development'],
                'icon' => '⚙️',
                'language' => 'ar',
            ],
            [
                'name' => 'Tech Vault',
                'name_en' => 'Tech Vault',
                'url' => 'https://www.youtube.com/@TechVault_',
                'description_ar' => 'خزينة التقنية',
                'description_en' => 'Tech Vault',
                'topics' => ['Technology', 'Programming'],
                'icon' => '🔐',
                'language' => 'ar',
            ],
            [
                'name' => 'Yalla Code',
                'name_en' => 'Yalla Code',
                'url' => 'https://www.youtube.com/@yallacode_',
                'description_ar' => 'يلا نبرمج - محتوى برمجي تفاعلي',
                'description_en' => 'Interactive programming content',
                'topics' => ['Programming', 'Coding'],
                'icon' => '🚀',
                'language' => 'ar',
            ],
            [
                'name' => 'Ahmed Elfakharany',
                'name_en' => 'Ahmed Elfakharany',
                'url' => 'https://www.youtube.com/@AhmedElfakharany',
                'description_ar' => 'دورات Laravel و PHP المتقدمة',
                'description_en' => 'Advanced Laravel & PHP courses',
                'topics' => ['Laravel', 'PHP', 'Backend'],
                'icon' => '💎',
                'language' => 'ar',
            ],
            [
                'name' => 'Ahmed Elemam',
                'name_en' => 'Ahmed Elemam',
                'url' => 'https://www.youtube.com/@ahmdelemam',
                'description_ar' => 'محتوى برمجي متنوع',
                'description_en' => 'Various programming content',
                'topics' => ['Programming', 'Development'],
                'icon' => '👨‍🎓',
                'language' => 'ar',
            ],
            [
                'name' => '0xEid',
                'name_en' => '0xEid',
                'url' => 'https://www.youtube.com/@a0xEid',
                'description_ar' => 'محتوى تقني متخصص',
                'description_en' => 'Specialized technical content',
                'topics' => ['Programming', 'Tech'],
                'icon' => '🔧',
                'language' => 'ar',
            ],
            [
                'name' => 'Asoli Dev',
                'name_en' => 'Asoli Dev',
                'url' => 'https://www.youtube.com/@asoli_dev',
                'description_ar' => 'تطوير البرمجيات',
                'description_en' => 'Software development',
                'topics' => ['Software Development', 'Programming'],
                'icon' => '⚡',
                'language' => 'ar',
            ],
            [
                'name' => 'Mah Youssef',
                'name_en' => 'Mah Youssef',
                'url' => 'https://www.youtube.com/@mahyoussef',
                'description_ar' => 'محتوى برمجي تعليمي',
                'description_en' => 'Educational programming content',
                'topics' => ['Programming', 'Web Development'],
                'icon' => '🌐',
                'language' => 'ar',
            ],
            [
                'name' => 'Saleem Hadad',
                'name_en' => 'Saleem Hadad',
                'url' => 'https://www.youtube.com/@saleem-hadad',
                'description_ar' => 'Laravel و تطوير الويب',
                'description_en' => 'Laravel and web development',
                'topics' => ['Laravel', 'Web Development'],
                'icon' => '🎨',
                'language' => 'ar',
            ],
            [
                'name' => 'Dr. Ahmed Hagag',
                'name_en' => 'Dr. Ahmed Hagag',
                'url' => 'https://www.youtube.com/@dr.ahmedhagag',
                'description_ar' => 'محتوى أكاديمي في البرمجة',
                'description_en' => 'Academic programming content',
                'topics' => ['Computer Science', 'Programming'],
                'icon' => '🏫',
                'language' => 'ar',
            ],
            [
                'name' => 'Mr. Kindy',
                'name_en' => 'Mr. Kindy',
                'url' => 'https://www.youtube.com/@mrkindyCom',
                'description_ar' => 'تعليم البرمجة للمبتدئين',
                'description_en' => 'Teaching programming for beginners',
                'topics' => ['Programming Basics', 'Tutorials'],
                'icon' => '📖',
                'language' => 'ar',
            ],
            [
                'name' => 'Tres Merge',
                'name_en' => 'Tres Merge',
                'url' => 'https://www.youtube.com/@tresmerge',
                'description_ar' => 'محتوى تقني متقدم',
                'description_en' => 'Advanced technical content',
                'topics' => ['Advanced Programming', 'Tech'],
                'icon' => '🔀',
                'language' => 'ar',
            ],
            [
                'name' => 'Codezilla',
                'name_en' => 'Codezilla',
                'url' => 'https://www.youtube.com/@codezilla',
                'description_ar' => 'دورات برمجية شاملة وتطوير المهارات التقنية',
                'description_en' => 'Comprehensive programming courses and technical skill development',
                'topics' => ['Programming', 'Web Development', 'Tutorials'],
                'icon' => '🦖',
                'language' => 'ar',
            ],
            [
                'name' => 'TheNewBaghdad',
                'name_en' => 'TheNewBaghdad',
                'url' => 'https://www.youtube.com/@TheNewBaghdad',
                'description_ar' => 'دروس برمجية متقدمة ومشاريع عملية',
                'description_en' => 'Advanced programming tutorials and practical projects',
                'topics' => ['Programming', 'Projects', 'Advanced Topics'],
                'icon' => '🏛️',
                'language' => 'ar',
            ],
            [
                'name' => 'Unique Coderz Academy',
                'name_en' => 'Unique Coderz Academy',
                'url' => 'https://www.youtube.com/@UniqueCoderzAcademy',
                'description_ar' => 'أكاديمية متخصصة في تعليم البرمجة والتطوير',
                'description_en' => 'Academy specialized in programming and development education',
                'topics' => ['Programming', 'Web Development', 'Mobile'],
                'icon' => '🎓',
                'language' => 'ar',
            ],
            [
                'name' => 'Mohamed Elsherif',
                'name_en' => 'Mohamed Elsherif',
                'url' => 'https://www.youtube.com/@MohamedElsherif',
                'description_ar' => 'مهارات مهنية ونصائح للمبرمجين',
                'description_en' => 'Professional skills and tips for programmers',
                'topics' => ['Career', 'Professional Skills', 'Programming'],
                'icon' => '💼',
                'language' => 'ar',
            ],
            [
                'name' => 'كورسات',
                'name_en' => 'Courses',
                'url' => 'https://www.youtube.com/@Coursat',
                'description_ar' => 'دورات برمجية مجانية وشاملة',
                'description_en' => 'Free and comprehensive programming courses',
                'topics' => ['Courses', 'Programming', 'Learning'],
                'icon' => '📖',
                'language' => 'ar',
            ],
            [
                'name' => 'غريب الشيخ',
                'name_en' => 'Ghareeb Elshaikh',
                'url' => 'https://www.youtube.com/@GhareebElshaikh',
                'description_ar' => 'تعليم البرمجة بطريقة عملية ومبسطة',
                'description_en' => 'Teaching programming in a practical and simplified way',
                'topics' => ['Programming', 'Tutorials', 'Arabic'],
                'icon' => '👨‍💻',
                'language' => 'ar',
            ],
        ];
    }

    public function render()
    {
        return view('livewire.student.youtube-channels');
    }
}
